# Generated by Django 4.1.7 on 2023-02-26 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.PositiveIntegerField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
    ]
