# Generated by Django 4.1.7 on 2023-02-27 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_person_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('game_name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('game_pic', models.ImageField(blank=True, null=True, upload_to='static')),
            ],
        ),
    ]
