# Generated by Django 4.1.7 on 2023-02-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_playstation_game_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='playstation',
            name='game_img',
            field=models.ImageField(blank=True, null=True, upload_to='my_app/static/media'),
        ),
    ]
