# Generated by Django 4.1.7 on 2023-02-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_nintendo_playstation_image_alter_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playstation',
            name='image',
        ),
    ]
