# Generated by Django 4.1.7 on 2023-03-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_playstation_game_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='nintendo',
            name='game_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
