# Generated by Django 4.1.7 on 2023-03-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_nintendo_game_img'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nintendo',
            table='Nintendo',
        ),
        migrations.AlterModelTable(
            name='playstation',
            table='Playstation',
        ),
    ]
