# Generated by Django 3.2.12 on 2023-03-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_alter_nintendo_table_alter_playstation_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console_number', models.PositiveIntegerField(blank=True, null=True)),
                ('console_name', models.CharField(max_length=50)),
                ('game_name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('game_img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('game_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pc_minimum_requirements', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console_name', models.CharField(max_length=50)),
                ('game_name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('game_img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
