# Generated by Django 4.1.7 on 2023-03-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_oldschool_pc_xbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='nintendo',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
