# Generated by Django 4.1.7 on 2023-03-07 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0014_nintendo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nintendo',
            name='name',
        ),
        migrations.AddField(
            model_name='nintendo',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
