# Generated by Django 4.1.7 on 2023-03-07 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0015_remove_nintendo_name_nintendo_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nintendo',
            name='uploader',
        ),
        migrations.AddField(
            model_name='nintendo',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
