# Generated by Django 4.1.7 on 2023-03-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_remove_nintendo_uploader_nintendo_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nintendo',
            name='added_by',
        ),
    ]
