# Generated by Django 4.1.7 on 2023-03-08 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_oldschool_user_pc_user_playstation_user_xbox_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nintendo',
            name='user',
        ),
        migrations.AddField(
            model_name='nintendo',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.person'),
        ),
    ]
