# Generated by Django 4.1.7 on 2023-03-08 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_remove_nintendo_user_nintendo_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldschool',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playstation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='xbox',
            name='user',
        ),
        migrations.AddField(
            model_name='oldschool',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.person'),
        ),
        migrations.AddField(
            model_name='pc',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.person'),
        ),
        migrations.AddField(
            model_name='playstation',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.person'),
        ),
        migrations.AddField(
            model_name='xbox',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.person'),
        ),
    ]
